import os.path
from setuptools import setup

setup(
    name="VideoHash",
    packages=["videohash"],
    version="1.0",
    keywords=[
        "videohash",
        "near duplicate video detection",
        "NDVD",
        "perceptual video hashing",
        "video hashing",
        "near duplicate video",
        "compare videos",
        "video",
        "video diff",
    ],
    install_requires=["ImageHash", "Pillow", "yt-dlp"],
    python_requires=">=3.6",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Intended Audience :: End Users/Desktop",
        "Intended Audience :: Information Technology",
        "Operating System :: MacOS",
        "Operating System :: Microsoft :: Windows",
        "Operating System :: POSIX",
        "Operating System :: POSIX :: Linux",
        "Operating System :: POSIX :: BSD",
        "Topic :: Multimedia :: Video",
        "Natural Language :: English",
        "Topic :: Software Development :: Build Tools",
        "Topic :: Scientific/Engineering :: Image Recognition",
        "Typing :: Typed",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: Implementation :: CPython",
    ],
    project_urls={
        "Source": "https://github.com/akamhy/videohash",
        "Documentation": "https://github.com/akamhy/videohash/wiki",
        "Tracker": "https://github.com/akamhy/videohash/issues",
    },
)
